#!/bin/sh

CURRENT_DIRECTORY="`pwd`"

# Verify that XCode is installed.
if [[ ! "$(type -P gcc)" && "$OSTYPE" =~ ^darwin ]]; then
  e_error "XCode or the XCode Command Line Tools must be installed first."
  exit 1
fi

# Install Homebrew.
if [[ ! "$(type -P brew)" ]]; then
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
fi

# Install Homebrew Cask.
if [ ! "$(brew tap | grep phinze/cask)" ]; then
  brew tap phinze/cask
fi

# Update Homebrew and Homebrew Cask.
brew update
brew cleanup

# Install Homebrew and Homebrew Cask formulas.
brew install bash brew-cask git node packer phantomjs python rbenv ruby-build the_silver_searcher tmux
brew cask install airfoil alfred caffeine dropbox google-chrome-canary google-hangouts gpgtools linkinus one-password spotify sublime-text vagrant virtualbox
brew cask alfred link

# Checkout dotfiles repository.
if [ -d "$HOME/.dotfiles" ]; then
  cd $HOME/.dotfiles && git pull origin master && cd $CURRENT_DIRECTORY
else
  git clone https://github.com/bradgignac/dotfiles $HOME/.dotfiles
fi

# Symlink Sublime Text binary.
ln -s "$HOME/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

# Symlink dotfiles.
for source in `find $HOME/.dotfiles -name "*.symlink"`
do
  destination="$HOME/`basename \"${source%.*}\"`"
  ln -fs $source $destination
done

# Immediately load profile changes.
source $HOME/.bash_profile
